version: '3.3'
services:

  pipeline-sentiment_analysis:
      build: ./pipelines/sentiment_analysis
      container_name: pipeline-sentiment_analysis
      restart: always
      volumes:
        - ./pipelines/sentiment_analysis/mnt/:/tmp/
      command: tail -F anything
  pipeline-extraction-twitter:
      build: ./pipelines/extraction-twitter
      container_name: pipeline-extraction-twitter
      restart: always
      volumes:
        - ./pipelines/extraction-twitter/mnt/:/tmp/
      command: tail -F anything
  mongo:
    build: ./mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
  mongo_seed:
    build: ./mongo_seed
    links:
      - mongo
    ports:
      - 9000
    environment:
      - MONGO_URI=mongodb:27017/RawDataDB
