version: '3.3'
services:
  pipeline-sentiment_analysis:
      build: ./pipelines/sentiment_analysis
      container_name: pipeline-sentiment_analysis
      restart: always
      volumes:
        - ./pipelines/sentiment_analysis/mnt/:/tmp/
      command: tail -F anything