version: '3.3'
services:
  pipeline-extraction-twitter:
      build: ./pipelines/extraction-twitter
      container_name: pipeline-extraction-twitter
      restart: always
      volumes:
        - ./pipelines/extraction-twitter/mnt/:/tmp/
      command: tail -F anything