version: '3.3'
services:
  metabase:
    image: metabase/metabase:v0.46.8
    container_name: metabase
    restart: always
    volumes:
      - ./metabase/mnt/metabase.db:/metabase.db
    ports:
      - 3000:3000
    networks:
      - projetm1-network

  pipeline-sentiment_analysis:
    build: ./pipelines/sentiment_analysis
    container_name: pipeline-sentiment_analysis
    restart: always
    volumes:
      - ./pipelines/sentiment_analysis/mnt/:/tmp/
    command: tail -F anything
    networks:
      - projetm1-network

  pipeline-extraction-twitter:
    build: ./pipelines/extraction-twitter
    container_name: pipeline-extraction-twitter
    restart: always
    volumes:
      - ./pipelines/extraction-twitter/mnt/:/tmp/
    command: tail -F anything
    networks:
      - projetm1-network

  mongo:
    build: ./mongo
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - projetm1-network

  mongo_seed:
    build: ./mongo_seed
    links:
      - mongo
    ports:
      - 9000
    environment:
      - MONGO_URI=mongodb:27017/RawDataDB
    networks:
      - projetm1-network

networks:
  projetm1-network:
    driver: bridge